<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AngleSharp" Version="1.7.2" />
    <PackageVersion Include="CommunityToolkit.WinUI.Behaviors" Version="8.3.260402-preview2" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Web.WebView2" Version="1.0.3719.77" />
    <PackageVersion Include="Microsoft.WindowsAppSDK.Foundation" Version="2.3.9" />
    <PackageVersion Include="Microsoft.WindowsAppSDK.InteractiveExperiences" Version="2.1.6" />
    <PackageVersion Include="Microsoft.WindowsAppSDK.Runtime" Version="2.4.0" />
    <PackageVersion Include="Microsoft.WindowsAppSDK.WinUI" Version="2.3.6" />
    <PackageVersion Include="WixToolset.Bal.wixext" Version="5.0.2" />
    <PackageVersion Include="WixToolset.Netfx.wixext" Version="5.0.2" />
    <PackageVersion Include="WixToolset.Util.wixext" Version="5.0.2" />
  </ItemGroup>
</Project>
